GUI:
  length_waterfall: 1000
  refresh_time: 50
camera_fiber:
  config:
    ROI:
    - - 1
      - 1280
    - - 1
      - 960
    auto_exposure: false
    auto_gain: false
    binning:
    - 1
    - 1
    buffer_size: 200MB
    exposure: 100ms
    gain: 14.0
    pixel_format: Mono8
  init: daA1280
  model: basler
  model_camera: Dart
camera_microscope:
  config:
    ROI:
    - - 1
      - 1920
    - - 1
      - 1200
    auto_exposure: false
    auto_gain: false
    buffer_size: 2000MB
    exposure: 500us
    gain: 0.0
    pixel_format: Mono12
  init: a2A1920
  model: basler
  model_camera: ACE
defaults:
  alignment: null
  core_width: 30
  devices_loading_timeout: 10s
  fiber_center: null
  laser_focusing:
    high:
      exposure: 400ms
      gain: 10.0
    low:
      exposure: 10us
      gain: 0.0
  microscope_center: null
  microscope_focusing:
    high:
      exposure: 50ms
      gain: 10.0
    low:
      exposure: 5ms
      gain: 0.0
electronics:
  arduino:
    baud_rate: 115200
    port: null
  focus_axis: 3
  horizontal_axis: 1
  laser:
    power: 99
  led_fiber: 2
  led_initialising: 5
  led_power: 3
  led_processing: 4
  led_ready: 6
  led_side: 0
  led_top: 1
  vertical_axis: 2
info:
  files:
    description: Test with water
    filename: Waterfall_{description}_{i}.h5
    folder: '%HOMEPATH%\NanoCET'
    max_memory: 2500
  user: User
