# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2021.10.8-h5b45459_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/icc_rt-2019.0.0-h0cc432a_1.conda
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2021.2.0-haa95532_616.conda
https://conda.anaconda.org/conda-forge/win-64/msys2-conda-epoch-20160418-1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pandoc-2.14.1-h8ffe710_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.27.29016-h5e58377_2.conda
https://conda.anaconda.org/conda-forge/win-64/winpty-0.4.3-4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/m2w64-gmp-6.1.0-2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/m2w64-libwinpthread-git-5.0.0.4634.697f757-2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl-2021.2.0-haa95532_296.conda
https://repo.anaconda.com/pkgs/main/win-64/vc-14.2-h21ff451_1.conda
https://conda.anaconda.org/conda-forge/win-64/blas-1.0-mkl.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/brotli-1.0.9-ha925a31_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/bzip2-1.0.8-he774522_0.conda
https://repo.anaconda.com/pkgs/main/win-64/cfitsio-3.470-he774522_6.conda
https://repo.anaconda.com/pkgs/main/win-64/charls-2.2.0-h6c2663c_0.conda
https://repo.anaconda.com/pkgs/main/win-64/giflib-5.2.1-h62dcd97_0.conda
https://repo.anaconda.com/pkgs/main/win-64/icu-58.2-ha925a31_3.conda
https://repo.anaconda.com/pkgs/main/win-64/jpeg-9b-hb83a4c4_2.conda
https://repo.anaconda.com/pkgs/main/win-64/lerc-2.2.1-hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libaec-1.0.4-h33f27b4_1.conda
https://repo.anaconda.com/pkgs/main/win-64/libdeflate-1.7-h2bbff1b_5.conda
https://conda.anaconda.org/conda-forge/win-64/libsodium-1.0.18-h8d14728_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libusb-1.0.24-h0e60522_2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libzopfli-1.0.3-ha925a31_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/lz4-c-1.9.3-h2bbff1b_0.conda
https://conda.anaconda.org/conda-forge/win-64/m2w64-gcc-libs-core-5.3.0-7.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/openssl-1.1.1n-h8ffe710_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/snappy-1.1.8-h33f27b4_0.conda
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.36.0-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tbb-2021.5.0-h59b6b97_0.conda
https://conda.anaconda.org/conda-forge/win-64/tk-8.6.10-he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/xz-5.2.5-h62dcd97_0.conda
https://conda.anaconda.org/conda-forge/win-64/yaml-0.2.5-he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/zfp-0.5.5-hd77b12b_6.conda
https://repo.anaconda.com/pkgs/main/win-64/zlib-1.2.11-h62dcd97_4.conda
https://repo.anaconda.com/pkgs/main/win-64/hdf5-1.10.6-h7ebc959_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libpng-1.6.37-h2a8f88b_0.conda
https://conda.anaconda.org/conda-forge/win-64/m2w64-gcc-libgfortran-5.3.0-6.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/python-3.8.10-hdbf39b2_7.conda
https://conda.anaconda.org/conda-forge/win-64/zeromq-4.3.4-h0e60522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/zstd-1.4.9-h19a0ad4_0.conda
https://conda.anaconda.org/conda-forge/noarch/async_generator-1.10-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/attrs-21.2.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backcall-0.2.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports-1.0-py_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/blosc-1.21.0-h19a0ad4_0.conda
https://conda.anaconda.org/conda-forge/noarch/charset-normalizer-2.0.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cloudpickle-1.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/colorama-0.4.4-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-5.0.9-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/defusedxml-0.7.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/entrypoints-0.3-pyhd8ed1ab_1003.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/freetype-2.10.4-hd328e21_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/fsspec-2021.7.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/idna-3.1-pyhd3deb0d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipython_genutils-0.2.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/json5-0.9.5-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/kiwisolver-1.3.1-py38hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libtiff-4.2.0-hd0e1b90_0.conda
https://repo.anaconda.com/pkgs/main/win-64/llvmlite-0.37.0-py38h23ce68f_2.conda
https://repo.anaconda.com/pkgs/main/win-64/locket-0.2.1-py38haa95532_1.conda
https://conda.anaconda.org/conda-forge/win-64/m2w64-gcc-libs-5.3.0-7.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nest-asyncio-1.5.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/networkx-2.6.2-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/olefile-0.46-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pandocfilters-1.4.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/parso-0.8.2-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pickleshare-0.7.5-py_1003.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prometheus_client-0.11.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.20-pyh9f0ad1d_2.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyreadline-2.1-py38_1.conda
https://conda.anaconda.org/conda-forge/noarch/pyserial-3.5-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/python_abi-3.8-2_cp38.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pytz-2021.1-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyusb-1.2.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyyaml-5.4.1-py38h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/qt-5.9.7-vc14h73c81de_0.conda
https://conda.anaconda.org/conda-forge/noarch/send2trash-1.7.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/sip-4.19.13-py38ha925a31_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/testpath-0.5.0-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/toolz-0.11.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/tornado-6.1-py38h2bbff1b_0.conda
https://conda.anaconda.org/conda-forge/noarch/typing_extensions-3.10.0.0-pyha770c72_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/webencodings-0.5.1-py_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.36.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/wincertstore-0.2-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/zipp-3.5.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/babel-2.9.1-pyh44b312d_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/certifi-2021.10.8-py38haa244fe_2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cffi-1.14.6-py38hd8c33c5_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/chardet-4.0.0-py38haa244fe_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/cycler-0.10.0-py38_0.conda
https://repo.anaconda.com/pkgs/main/win-64/cytoolz-0.11.0-py38he774522_0.conda
https://conda.anaconda.org/conda-forge/win-64/debugpy-1.4.1-py38h885f38d_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/importlib-metadata-4.6.1-py38haa244fe_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/importlib_resources-5.2.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jedi-0.18.0-py38haa244fe_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/lcms2-2.12-h83e58a3_0.conda
https://conda.anaconda.org/conda-forge/win-64/markupsafe-2.0.1-py38h294d835_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mistune-0.8.4-py38h294d835_1004.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl-service-2.3.0-py38h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/openjpeg-2.3.0-h5ec785f_1.conda
https://conda.anaconda.org/conda-forge/noarch/packaging-21.0-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/partd-1.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pillow-8.3.1-py38h4fa10fc_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pyqt-5.9.2-py38ha925a31_4.conda
https://conda.anaconda.org/conda-forge/win-64/pyrsistent-0.17.3-py38h294d835_2.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-pyhd3eb1b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyvisa-1.11.3-py38haa244fe_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pywin32-300-py38h294d835_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pywinpty-0.5.7-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyzmq-22.1.0-py38h09162b1_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/sniffio-1.2.0-py38haa244fe_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/traitlets-5.0.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/websocket-client-0.57.0-py38haa244fe_4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/win_inet_pton-1.1.0-py38haa244fe_2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/anyio-3.3.0-py38haa244fe_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/argon2-cffi-20.1.0-py38h294d835_2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/brotlipy-0.7.0-py38h294d835_1001.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cryptography-3.4.7-py38hd7da0ea_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/dask-core-2021.7.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/importlib_metadata-4.6.1-hd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jinja2-3.0.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jupyter_core-4.7.1-py38haa244fe_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/matplotlib-inline-0.1.2-pyhd8ed1ab_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.20.2-py38hc2deb75_0.conda
https://conda.anaconda.org/conda-forge/win-64/pysocks-1.7.1-py38haa244fe_3.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyvisa-py-0.5.2-pyh44b312d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/setuptools-52.0.0-py38haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/terminado-0.9.4-py38haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/backports.functools_lru_cache-1.6.4-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/bleach-3.3.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jsonschema-3.2.0-pyhd8ed1ab_3.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_client-6.1.12-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pint-0.17-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pip-21.1.3-py38haa95532_0.conda
https://conda.anaconda.org/conda-forge/noarch/pygments-2.9.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyopenssl-20.0.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyterlab_pygments-0.1.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbformat-5.1.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/urllib3-1.26.6-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wcwidth-0.2.5-pyh9f0ad1d_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbclient-0.5.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prompt-toolkit-3.0.19-pyha770c72_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/requests-2.26.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ipython-7.25.0-py38h43734a8_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/nbconvert-6.1.0-py38haa244fe_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/requests-unixsocket-0.2.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ipykernel-6.0.3-py38h43734a8_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_server-1.10.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyterlab_server-2.6.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/notebook-6.4.0-pyha770c72_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbclassic-0.3.1-pyhd8ed1ab_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyterlab-3.1.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/imageio-2.9.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyqtgraph-0.11.0-py_0.conda
https://repo.anaconda.com/pkgs/main/win-64/h5py-3.6.0-py38h3de5c98_0.conda
https://repo.anaconda.com/pkgs/main/win-64/imagecodecs-2021.6.8-py38h5da4933_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tifffile-2021.7.2-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/win-64/matplotlib-3.3.4-py38haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/matplotlib-base-3.3.4-py38h49ac443_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_fft-1.3.0-py38h277e83a_2.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_random-1.2.1-py38hf11a4ad_2.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.20.2-py38ha4e8547_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numba-0.54.1-py38hf11a4ad_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pandas-1.2.5-py38hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pywavelets-1.1.1-py38he774522_2.conda
https://repo.anaconda.com/pkgs/main/win-64/scipy-1.6.2-py38h66253e8_1.conda
https://repo.anaconda.com/pkgs/main/win-64/scikit-image-0.18.1-py38hf11a4ad_0.conda
https://conda.anaconda.org/conda-forge/noarch/trackpy-0.5.0-pyhd8ed1ab_0.tar.bz2
